import { StyleSheet } from "react-native";
import Fonts from "../../styles/fonts";
import Colors from "../../styles/colors";

const Style = StyleSheet.create({
  container: {
    flex: 1,
    opacity: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    color: Colors.purple,
    fontSize: Fonts.size.font22,
    textAlign: "center",
    height: 50,
    width: 234,
    marginTop: 10,
  },
  scrollView: {
    width: "95%",
    height: "auto",
    backgroundColor: "#fff",
  },
  safeAreaView: {
    width: "100%",
    height: "100%",
    display: "flex",
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "space-between",
    alignItems: "center",
  },
  info: {
    width: 300,
    backgroundColor: "#fff",
    borderRadius: 10,
    marginTop: 25,
    marginLeft: 37,
    marginBottom: 5,
    alignItems: "center",
    borderRadius: 5,
  },
  titleDuvida: {
    fontSize: Fonts.size.font12,
    //fontFamily: 'Montserrat-SemiBold',
    color: Colors.purple,
    marginTop: 5,
    marginLeft: 5,
  },
  descutionDuvida: {
    fontSize: Fonts.size.font10,
    //fontFamily: 'Montserrat-SemiBold',
    color: Colors.purple,
    marginTop: 2,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
  },
  nextSteps: {
    width: "auto",
  },
  titleNextSteps: {
    fontSize: Fonts.size.font16,
    //fontFamily: 'Montserrat-Regular',
    color: Colors.purple,
    marginTop: 2,
    marginLeft: 15,
    marginRight: 5,
    marginBottom: 5,
  },

  descriptionNextSteps: {
    fontSize: Fonts.size.font14,
    //fontFamily: 'Montserrat-Regular',
    color: Colors.purple,
    marginTop: 2,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 5,
  },
  recommendations: {
    width: "auto",
    marginTop: 5,
  },
  products: {
    alignItems: "center",
    justifyContent: "space-between",
    width: "auto",
    borderRadius: 10,
    borderColor: "#000",
    shadowOpacity: 0.1,
    marginTop: 5,
    marginBottom: 5,
  },
  subProducts: {
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  backProducts: {
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    borderRadius: 20,
    width: 325,
    margin: 1,
    height: 170,
  },
  titleProduct: {
    fontSize: 16,
    //fontFamily: 'Montserrat-Regular',
    color: Colors.purple,
    marginTop: 20,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
  },
  infoProducts: {
    justifyContent: "space-between",
    alignItems: "center",
    width: 250,
    height: "auto",
    flexDirection: "row",
    marginTop: -15,
    marginLeft: -20,
  },
  positionProducts: {
    backgroundColor: Colors.green3,
    width: 35,
    height: 35,
    textAlign: "center",
    borderRadius: 20,
  },
  subPositionProducts: {
    color: "#fff",
    textAlign: "center",
    alignItems: "center",
    marginTop: 9,
    marginLeft: -3,
  },
  positionDescription: {
    marginLeft: 10,
  },
  description: {
    fontSize: Fonts.size.font14,
    textAlign: "left",
    //fontFamily: 'Montserrat-Regular',
    color: Colors.black,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
  },
  positionButtonPay: {
    marginLeft: 170,
    width: 100,
    height: 30,
    borderRadius: 20,
    borderColor: "#4EA6F8",

    shadowColor: "#4EA6F8",
    shadowOpacity: 0.1,
    backgroundColor: "#fff",
    alignItems: "center",
    marginBottom: 10,
  },
  textButtonPay: {
    marginTop: 3,
    color: "#4EA6F8",
  },
});

export default Style;
